# Generated by Django 3.1.3 on 2020-12-11 19:33

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_elder_request_service'),
    ]

    operations = [
        migrations.AddField(
            model_name='testvolunteer',
            name='elder_ids',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), null=True, size=None),
        ),
    ]
