# Generated by Django 3.1.3 on 2020-12-12 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_testvolunteer_elder_ids'),
    ]

    operations = [
        migrations.CreateModel(
            name='AddElder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('elder', models.IntegerField(default=1)),
                ('volunteer', models.IntegerField(default=1)),
            ],
        ),
    ]
