# Generated by Django 3.1.3 on 2020-12-12 09:22

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_addelder'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testvolunteer',
            name='elder_ids',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), default=list, null=True, size=None),
        ),
    ]
