# Generated by Django 3.1.3 on 2020-12-12 09:25

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20201212_1452'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testvolunteer',
            name='elder_ids',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(default=0), default=list, size=None),
        ),
    ]
